### ISSUE TITLE
Incompatible with ui-select or selectize

### ISSUE THREAD

**Issue by CarbonFactory** [huei90/angular-validation#95] opened 2015-03-15 10:34 UTC
`Error: [$compile:multidir] Multiple directives [selectize, validator] asking for new/isolated scope on: <select class="ng-pristine ng-untouched ng-valid" validator="huei" data-ng-model="customer.salesPerson" data-placeholder="Sales Person" name="salesPerson" data-selectize="" data-options="">`

Duplicate of  #65

**Comment by huei90** [comment] 2015-05-11 04:03
@CarbonFactory Sorry for the late reply.

Any update on this?

**Comment by rreeve07** [comment] 2015-05-12 14:21
I ran into the same issue. The error is caused by both ui-select and angular-validation asking for isolated scopes on the same element from within their respective directives. This is not something that angular currently supports, and I am not sure if they ever will.

The best fix--imo--would be to change the validator directive to remove the isolated scope. This would make the directive much more flexible.

Example plnkr: http://plnkr.co/edit/P7U4e2tmGCUL6pyaHkbR?p=preview

**Comment by huei90** [comment] 2015-05-12 16:37
@rreeve07 It can be fixed by using your case.

In this way? `ng-model` `validator` on the `<ui-select` ?
```html
 <ui-select multiple ng-model="multipleDemo.colors" ng-disabled="disabled" style="width: 300px;" validator="required">
    <ui-select-match placeholder="Select colors...">{{$item}}</ui-select-match>
    <ui-select-choices repeat="color in availableColors | filter:$select.search">
      {{color}}
    </ui-select-choices>
  </ui-select>
```

**Comment by CarbonFactory** [comment] 2015-05-26 10:09
@huei90 Sorry for the delay. I switched to [Kelp404](https://github.com/kelp404/angular-validator). I'll switch back once we have a workaround/fix for this.

**Comment by huei90** [comment] 2015-05-26 10:13
it's ok

**Comment by dmitry-dedukhin** [comment] 2015-05-27 09:31
As a workaround you can use additional hidden input with validation on it:

```html
<ui-select ng-model="someVal">
</ui-select>
<input type="hidden" ng-model="someVal" validator="required">
```

**Comment by gustavolira** [comment] 2015-08-28 02:05
Hi,
Any fix for this issue? I'm facing this same problem, I tried the workaround but did not work;

**Comment by newpaulinhu** [comment] 2015-09-04 12:13
Any fix for this issue?

**Comment by hungdoan2** [comment] 2015-09-18 10:52
@huei90 . The problem here is [multiple directives are applied to the same DOM element](https://docs.angularjs.org/error/$compile/multidir?p0=uiSelect&p1=validator&p2=new%2Fisolated%20scope&p3=%3Cdiv%20class%3D%22ui-select-container%20ui-select-multiple%20ui-select-bootstrap%20dropdown%20form-control%22%20ng-class%3D%22%7Bopen:%20$select.open%7D%22%20ng-model%3D%22multipleDemo.colors%22%20ng-disabled%3D%22disabled%22%20style%3D%22width:%20300px;%22%20validator%3D%22required%22%3E).
If we remove the `scope` isolation define at here: 
https://github.com/huei90/angular-validation/blob/master/src/directive.js#L162-L173
``` javascript
 return {
	restrict: 'A',
	require: 'ngModel',
	scope: { // <== remove this implement, and use angularjs $parse and $scope.$watch instead
		model: '=ngModel',
		initialValidity: '=initialValidity',
		validCallback: '&',
		invalidCallback: '&',
		messageId: '@'
	},
	link: function(scope, element, attrs, ctrl) {
```
And I'll be done.

**Comment by Nazanin1369** [comment] 2015-09-22 20:54
Any one fixing this?  Otherwise I can go ahead

**Comment by huei90** [comment] 2015-09-23 01:15
welcome @Nazanin1369 Need your help.

**Comment by huei90** [comment] 2015-10-06 03:52
Duplicate
https://github.com/huei90/angular-validation/issues/113

**Comment by huei90** [comment] 2015-11-26 08:47
I'm not focus on this fix now. Need help from you.

**Comment by Nazanin1369** [comment] 2015-12-06 05:25
I believe this fix has merged. @huei90 ?

**Comment by huei90** [comment] 2015-12-07 02:17
I believe too.

**Closed** 2015-12-07 02:41 UTC
Labels: bug, pending-fix-need-contribution
