### ISSUE TITLE
validation-reset and has-error input

### ISSUE THREAD

**Issue by alexgoroshko** [huei90/angular-validation#135] opened 2015-08-19 23:02 UTC
I extended validation provider like that: 

![image](https://cloud.githubusercontent.com/assets/3901682/9370994/94d10ed2-469a-11e5-95f7-f286dc0061f1.png)

And then I just put some invalid data to input to get validation error

![image](https://cloud.githubusercontent.com/assets/3901682/9371057/015c9eb8-469b-11e5-8518-0987b7fc6592.png)

As you see angular validation properly added has-error class to the parent div and added a validation error message.
But when I click reset validation, has-error class appears on the first input and is still on the second one, but error message disappear

![image](https://cloud.githubusercontent.com/assets/3901682/9371182/431f8bca-469c-11e5-85df-f663ddb97155.png)

What am I doing wrong?

**Comment by huei90** [comment] 2015-08-20 02:14
Check your code again. I saw you add and remove class on the `element.parent()`, might be the parent problem. Check again.

**Comment by alexgoroshko** [comment] 2015-08-20 02:28
Just added console.log() to my code snippet:

angular.extend($validationProvider, {
            validCallback: function (element) {
                console.log("validCallback");
                element.parent().removeClass('has-error');
            },
            invalidCallback: function (element) {
                console.log("invalidCallback");
                element.parent().addClass('has-error');
            }
        });

and then I clicked button with validation-reset on it and I've got two invalidCallback events

![image](https://cloud.githubusercontent.com/assets/3901682/9374214/351af9d4-46b9-11e5-836b-58a864de7f92.png)

**Comment by alexgoroshko** [comment] 2015-08-20 02:32
Pay attention that these inputs have validators. It seems like validation-reset fires invalidCallback

**Comment by huei90** [comment] 2015-08-20 02:36
Yes you are right.
https://github.com/huei90/angular-validation/blob/master/src/directive.js#L225-L243

The reset will manually remove the value and remove the invalid element, and might trigger the invalidcallback function.

Reset must be **clean**. This should be improve! Thanks @alexgoroshko

**Comment by alexgoroshko** [comment] 2015-08-20 04:00
But if you make clear reset validation (without events) it won't solve the problem. 
So I have such extension 

![image](https://cloud.githubusercontent.com/assets/3901682/9375410/d792265e-46c5-11e5-9b9d-e8d68bf655fd.png)

It means if there is a validation error so "angular-validation" adds has-error class to parent div (because I need bootstrap red border on invalid input). Then just try to reset validation and it will remove just validation error message and has-error class will be still on div. Have you any ideas how to correctly reset validation, just return to neutral state like it was before validating?

**Comment by alexgoroshko** [comment] 2015-08-20 04:03
Maybe add some reset-validation event where we will be able to set initial state like it's supposed to be before validation.

**Comment by huei90** [comment] 2015-08-20 04:03
Have you tried this when using angular-validation in Bootstrap?
https://github.com/huei90/angular-validation#integrating-with-twitter-bootstrap

**Comment by alexgoroshko** [comment] 2015-08-20 04:11
Yes, I have. I was talking about reset-validation, that if you want to reset form validation where already exist some validation errors it won't fire validCallback and 
$(element).parents('.form-group:first').removeClass('has-error'); 
won't be fired. Is it clear what I mean?

**Comment by huei90** [comment] 2015-08-20 04:12
Yes, i get your point. We need a better and real `reset` for the form.

**Comment by huei90** [comment] 2015-08-20 04:13
@Nazanin1369 Any opinion in this issue?

**Comment by alexgoroshko** [comment] 2015-08-20 15:55
Even in your demo http://huei90.github.io/angular-validation/ whe you jusr reload the page, input is clear, without ng-invalid class.

![image](https://cloud.githubusercontent.com/assets/3901682/9387919/58622916-4728-11e5-83b0-7116f52d10ed.png)

Then type just something wrong to get validation error. As you see for now input has a ng-invalid class.

![image](https://cloud.githubusercontent.com/assets/3901682/9388202/a1d74f80-4729-11e5-93d9-c74636072a04.png)

Then just reset the form. There is nothing happens with input, it's still all validation error classes

![image](https://cloud.githubusercontent.com/assets/3901682/9388253/e8e1a8f8-4729-11e5-92c2-23ac96964101.png)

**Comment by huei90** [comment] 2015-08-21 02:24
Yes, therefore

> We need a better and real reset for the form

**Comment by Nazanin1369** [comment] 2015-08-21 02:26
I will look into it

**Comment by huei90** [comment] 2015-09-16 02:57
Hi @alexgoroshko 
Sorry for the late fix.

The problem is fixed now. Please try again.

**Closed** 2015-09-16 03:06 UTC
Labels: Improvement
